### ISSUE TITLE
Custom bucket is ignored by `cluster-customize` operations

### ISSUE THREAD

**Issue by mjtko** [alces-software/clusterware#246]
When a custom bucket is supplied, it is ignored by `cluster-customize` operations (but is not ignored when handling account profiles applied at boot):

The following should be updated to match the value that (correctly) ends up in `cluster-customizer.rc`:

```
[root@login1(bumpy-mouse-dromedary) etc]# cat cluster-customizer/config.yml
profiles: []
repositories:
  feature: "s3://alces-flight-profiles-eu-west-1/2017.1/features"
  account: "s3://alces-flight-zzzzzzzzzzzzzzzzzzz/customizer"
```
